- src/main/scala/fs2/kafka/package.scala
- src/test/scala/fs2/kafka/KafkaSpec.scala
Add some additional sinks for batch committing offsets when they're wrapped in `Option`.
> Add some commit batch option sinks

- src/main/scala/fs2/kafka/KafkaConsumer.scala
Change to make `partitionedStream` and `parallelPartitionedStream` the same. This is mainly since  `partitionedStream` cannot be processed in parallel while still providing ordering guarantees, which can be confusing for library users. `parallelPartitionedStream` is kept as an alias of `partitionedStream`, for binary compatibility.
> Change to move parallelPartitionedStream to partitionedStream

- src/main/scala/fs2/kafka/KafkaConsumerActor.scala
`KafkaConsumerActor` previously used `Chunk#chain` but this incurs two extra conversions, first to `List` and then to `Buffer`. `ConsumerRecords` returns a Java `List`, which we now convert to a `Vector`, and `Chunk` can then use this without any conversions. `Chain` was originally used for fast concatenation, but that's for a small corner case which should rarely happen.
> Change to use Chunk#vector in KafkaConsumerActor

- src/main/scala/fs2/kafka/KafkaConsumer.scala
- src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
`fiber#join` would only complete successfully, and not propagate errors from`KafkaConsumerActor` (and the poll scheduler). This pull request changes `fiber#join` to propagate those errors. This also means that consumer errors are now propagated to streams.
> Change to propagate consumer errors to streams

- build.sbt
- docs/readme.md
> Update mdoc to 0.7.1

- src/main/scala/fs2/kafka/KafkaProducer.scala
Because the Java `KafkaProducer#close` uses blocking `Thread#join` to wait for other threads. Ideally, this should be run on a blocking `ExecutionContext`, but we can't change this without breaking binary compatibility. It's also a bit much to require a blocking context just for the close operation.
> Change to start Producer#close in a Fiber

- build.sbt
- src/main/scala/fs2/kafka/ProducerSettings.scala
- src/main/scala/fs2/kafka/internal/instances.scala
- src/test/scala/fs2/kafka/CommittableMessageSpec.scala
- src/test/scala/fs2/kafka/ProducerSettingsSpec.scala
- Add `ProducerSettings#withDeliveryTimeout`.
> Update Kafka to 2.1.0

- .scalafmt.conf
- src/main/scala/fs2/kafka/CommittableOffsetBatch.scala
> Add CommittableOffsetBatch#fromFoldableMap

- src/main/scala/fs2/kafka/package.scala
> Change to make fs2.kafka.Id public

- build.sbt
- src/main/scala/fs2/kafka/KafkaAdminClient.scala
- src/main/scala/fs2/kafka/KafkaProducer.scala
- src/main/scala/fs2/kafka/internal/syntax.scala
I've updated to Kafka 2.2.0.
There was a deprecation so I fixed that. Other than seems like there were no issues - tests passing etc.
> Update to Kafka 2.2.0

- src/main/scala/fs2/kafka/KafkaConsumer.scala
- src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
There's a race condition between the `Stream.repeatEval` issuing fetch requests and the `interruptWhen`, where fetch requests can be issued even after the interrupt `Deferred` has been completed. This pull request stops such requests from being issued while waiting on interruption.
> Change to prevent requests when partition revoked

- src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala
> Change to start polling after streaming started

- build.sbt
- src/test/scala/fs2/kafka/BaseSpec.scala
- Update scalatest to 3.0.7
- Update embedded-kafka to 2.2.0
- Update better-monadic-for to 0.3.0
> Update dependencies to latest versions

- build.sbt
- docs/src/main/mdoc/consumers.md
- docs/src/main/mdoc/producers.md
- modules/core/src/main/scala/fs2/kafka/ConsumerSettings.scala
- modules/core/src/test/scala/fs2/kafka/ConsumerSettingsSpec.scala
Also add `ConsumerSettings#withAllowAutoCreateTopics` and `withClientRack`.
> Update Kafka to 2.3.0

- .travis.yml
- build.sbt
> Revert "Update scala to 2.12.9"

- modules/core/src/main/scala/fs2/kafka/ConsumerSettings.scala
- modules/core/src/test/scala/fs2/kafka/ConsumerSettingsSpec.scala
Details here: https://kafka.apache.org/documentation/#static_membership
> Add ConsumerSettings#withGroupInstanceId

- modules/core/src/main/scala/fs2/kafka/KafkaProducer.scala
- modules/core/src/main/scala/fs2/kafka/ProducerRecords.scala
- modules/core/src/main/scala/fs2/kafka/ProducerResult.scala
- modules/core/src/main/scala/fs2/kafka/TransactionalKafkaProducer.scala
- modules/core/src/main/scala/fs2/kafka/package.scala
- modules/core/src/test/scala/fs2/kafka/KafkaProducerSpec.scala
- modules/core/src/test/scala/fs2/kafka/ProducerResultSpec.scala
As proposed in https://github.com/ovotech/fs2-kafka/pull/182#issuecomment-525091340.
> Use Chunk in ProducerRecords / ProducerResult.

- modules/core/src/main/scala/fs2/kafka/KafkaAdminClient.scala
- modules/core/src/test/scala/fs2/kafka/KafkaAdminClientSpec.scala
- modules/core/src/test/scala/fs2/kafka/internal/SynchronizedSpec.scala
It'd be great to have this functionality available :+1:
> Partitions altering

- modules/core/src/main/scala/fs2/kafka/KafkaProducer.scala
Very rough around the edges, but better than nothing for now. Feel free to edit of course.
> Add more info to produce

- docs/src/main/mdoc/admin.md
- modules/core/src/test/scala/fs2/kafka/KafkaAdminClientSpec.scala
- website/i18n/en.json
- website/sidebars.json
When I first looked around I didn't know there were functionalities around the admin client so I thought I'd create a small documentation page.
However I don't know / wasn't able to find out how the pages are organized on the website.
> Document admin client functionalities in a specific documentation page

- build.sbt
- docs/src/main/mdoc/admin.md
- modules/core/src/main/scala/fs2/kafka/KafkaAdminClient.scala
- modules/core/src/test/scala/fs2/kafka/BaseKafkaSpec.scala
- modules/core/src/test/scala/fs2/kafka/KafkaAdminClientSpec.scala
> add ACLs describe, crete, delete method in KafkaAdminClient

- modules/core/src/main/scala/fs2/kafka/Deserializer.scala
- modules/core/src/main/scala/fs2/kafka/RecordDeserializer.scala
- modules/core/src/main/scala/fs2/kafka/RecordSerializer.scala
- modules/core/src/main/scala/fs2/kafka/Serializer.scala
- modules/core/src/main/scala/fs2/kafka/package.scala
> Rename record serializers and deserializers

- build.sbt
- modules/core/src/test/scala/fs2/kafka/BaseSpec.scala
- modules/core/src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
- modules/vulcan/src/main/scala/fs2/kafka/vulcan/AvroDeserializer.scala
- Update cats-effect to 2.1.4
- Update kafka-avro-serializer to 5.5.1
- Update embedded-kafka to 2.6.0
- Update fs2 to 2.4.3
- Update discipline-scalatest to 2.0.0
> Update depedencies to latest versions

- build.sbt
- modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala
- modules/core/src/test/scala/fs2/kafka/KafkaAdminClientSpec.scala
This will be needed for scala 3 support 😥
> Drop better-monadic-for

- docs/src/main/mdoc/consumers.md
- modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala
Add docs for `KafkaConsumer#partitionedMapStream`
> Add docs for KafkaConsumer#partitionedMapStream

- .github/workflows/ci.yml
- build.sbt
> Revert "use github matrix for CI"

- build.sbt
- modules/core/src/main/scala/fs2/kafka/KafkaProducer.scala
- modules/core/src/main/scala/fs2/kafka/KafkaProducerConnection.scala
- modules/core/src/main/scala/fs2/kafka/ProducerResource.scala
- modules/core/src/main/scala/fs2/kafka/ProducerStream.scala
- modules/core/src/main/scala/fs2/kafka/TransactionalKafkaProducer.scala
- modules/core/src/main/scala/fs2/kafka/TransactionalProducerResource.scala
- modules/core/src/main/scala/fs2/kafka/TransactionalProducerStream.scala
- modules/core/src/main/scala/fs2/kafka/package.scala
- modules/core/src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
- modules/core/src/test/scala/fs2/kafka/KafkaProducerSpec.scala
> Fix producer regression in v1.2.0

- modules/core/src/main/scala/fs2/kafka/KafkaProducer.scala
- modules/core/src/main/scala/fs2/kafka/ProducerRecords.scala
- modules/core/src/main/scala/fs2/kafka/ProducerResult.scala
- modules/core/src/main/scala/fs2/kafka/TransactionalKafkaProducer.scala
- modules/core/src/main/scala/fs2/kafka/TransactionalProducerRecords.scala
- modules/core/src/main/scala/fs2/kafka/package.scala
- modules/core/src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
- modules/core/src/test/scala/fs2/kafka/ProducerRecordsSpec.scala
- modules/core/src/test/scala/fs2/kafka/TransactionalProducerRecordsSpec.scala
Resolves #410
I've created a `series/2.x` draft to open breaking PRs against.
> Move `P` type param in ProducerRecords to the left

- .github/workflows/notes.yml
Part of #494 and preparation for #495
> Run release-drafter against all series branches

- .github/workflows/ci.yml
- build.sbt
> remove master from ci target branches

- scalafix/input/src/main/scala/fix/PackageObjectMethodDeprecations.scala
- scalafix/output/src/main/scala/fix/PackageObjectMethodDeprecations.scala
- scalafix/rules/src/main/scala/fix/Fs2Kafka.scala
> fix scalafix rules

- modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala
- modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala
- modules/core/src/main/scala/fs2/kafka/internal/LogEntry.scala
Also narrows some types in KafkaConsumer
> Remove unneeded type parameters

- modules/core/src/main/scala/fs2/kafka/security/KafkaCredentialStore.scala
- modules/core/src/test/scala/fs2/kafka/security/KafkaCredentialStoreSpec.scala
Kafka requires newlines in the PEM to be replaced with spaces 🤦‍♂️
> Fix pem format

- .github/workflows/ci.yml
- build.sbt
- modules/core/src/test/scala/cats/tests/CatsEquality.scala
- modules/core/src/test/scala/cats/tests/CatsSuite.scala
Currently blocked on https://github.com/typelevel/cats-testkit-scalatest/pull/145
> Update 1.x to Scala 3 final

- build.sbt
@LMnet are you happy with these details?
> Update list of developers in build.sbt

- docs/src/main/mdoc/modules.md
> Add build.sbt instructions re: fs2-kafka-vulcan

- README.md
It could use some fleshing out, but it's a start.
Resolves #642
> Add a minimal readme

- build.sbt
Reverts fd4s/fs2-kafka#824
This brings in Kafka 3.
> Revert "Update kafka-avro-serializer to 7.0.1 in series/1.x"

- build.sbt
Reverts fd4s/fs2-kafka#822
This brings in Kafka 3.
> Revert "Update kafka-avro-serializer to 7.0.1"

- build.sbt
Reverts fd4s/fs2-kafka#828
confluent 7 updates kafka to 3.x - reverting this pending #702
> Revert "Update kafka-avro-serializer to 7.0.1 in series/3.x"

- website/i18n/en.json
- website/sidebars.json
> Publish certs docs

- modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala
- modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala
- modules/core/src/main/scala/fs2/kafka/internal/LogEntry.scala
> Revert #902

- build.sbt
- modules/core/src/main/scala/fs2/kafka/KafkaProducer.scala
- modules/core/src/main/scala/fs2/kafka/KafkaProducerConnection.scala
- modules/core/src/test/scala/fs2/kafka/KafkaProducerSpec.scala
> Add partitionFor for given topic with KafkaProducer

- .github/workflows/ci.yml
- build.sbt
- modules/core/src/main/scala-2.12/fs2/kafka/internal/converters.scala
- modules/core/src/main/scala-2.13+/fs2/kafka/internal/converters.scala
- modules/core/src/main/scala/fs2/kafka/Headers.scala
- modules/core/src/main/scala/fs2/kafka/KafkaAdminClient.scala
- modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala
- modules/core/src/main/scala/fs2/kafka/KafkaProducer.scala
- modules/core/src/main/scala/fs2/kafka/KafkaProducerConnection.scala
- modules/core/src/main/scala/fs2/kafka/TransactionalKafkaProducer.scala
- modules/core/src/main/scala/fs2/kafka/admin/MkAdminClient.scala
- modules/core/src/main/scala/fs2/kafka/consumer/MkConsumer.scala
- modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala
- modules/core/src/main/scala/fs2/kafka/internal/WithAdminClient.scala
- modules/core/src/main/scala/fs2/kafka/internal/WithConsumer.scala
- modules/core/src/main/scala/fs2/kafka/internal/WithProducer.scala
- modules/core/src/main/scala/fs2/kafka/internal/WithTransactionalProducer.scala
- modules/core/src/main/scala/fs2/kafka/internal/syntax.scala
- modules/core/src/main/scala/fs2/kafka/package.scala
- modules/core/src/main/scala/fs2/kafka/producer/MkProducer.scala
- modules/core/src/test/scala/fs2/kafka/BaseKafkaSpec.scala
- modules/core/src/test/scala/fs2/kafka/ConsumerRecordSpec.scala
- modules/core/src/test/scala/fs2/kafka/HeadersSpec.scala
- modules/core/src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
- modules/core/src/test/scala/fs2/kafka/TransactionalKafkaProducerSpec.scala
- modules/vulcan/src/main/scala/fs2/kafka/vulcan/AvroSettings.scala
- modules/vulcan/src/main/scala/fs2/kafka/vulcan/SchemaRegistryClientSettings.scala
Per #889 
Most changes come directly from the 2.x branch
> 3.x - Restore support for Scala 2.12

- .scala-steward.conf
- build.sbt
All missing latest versions for third party dependencies before releasing v3.1.0.
> Bump third party deps

- .github/workflows/ci.yml
- build.sbt
- modules/core/src/main/scala/fs2/kafka/internal/syntax.scala
- modules/core/src/test/scala/fs2/kafka/internal/SyntaxSpec.scala
- Publish artifact snapshots on `series/3.x`
- Use legacy Sonatype host
> Prepare release 3.1.0

- build.sbt
- modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala
> Use `Stream.iterable` instead of `Stream.emits`

- modules/core/src/main/scala/fs2/kafka/AdminClientSettings.scala
- modules/core/src/main/scala/fs2/kafka/package.scala
- modules/vulcan/src/main/scala/fs2/kafka/vulcan/AvroSettings.scala
> Revert "Remove deprecated methods (#1268)"

- build.sbt
Added me to the developers list 😊 
Also used the helper constructor `tlGitHubDev` for that.
> Add `aartigao` to developers list

- modules/core/src/main/scala/fs2/kafka/internal/Blocking.scala
Fixes #1321 
See discussion in the issue
> Revert #1126 as it's causing a performance regression

- modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala
- modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala
Ensures updates to `KafkaConsumerActor`'s internal state are applied together with the side-effects that support those updates by executing both together inside an uncancelable block. These changes ensure that changes made to the consumer are reflected in the internal state, and changes to the internal state are made visible to clients.
In the simplest cases, a sequence of `Ref.update`/`modify` and `Async.flatMap` was refactored to use `Ref.flatModify`, which offers the desired guarantees. In other cases, the relevant actions were explicitly wrapped in an `Async.uncancelable` block.
Where relevant, logging of state changes was treated as part of the uncancelable block. This is to avoid silent state changes, which may be hard to track down while debugging. Invocation of user-supplied …
> chore: make state transitions uncancelable
