build.sbt, src/main/scala/fs2/kafka/KafkaConsumer.scala, src/main/scala/fs2/kafka/KafkaConsumerActor.scala, src/main/scala/fs2/kafka/internal/syntax.scala
We already require a `ExecutionContext` for shifting (blocking) calls to the underlying Java consumer. However, if that `ExecutionContext` is backed by more than one thread, we still need locking to avoid concurrent modification issues when closing the consumer. This is not an issue if you're already using the default `consumerExecutionContextStream`, as it uses a single thread.
=> Use MVar for consumer locking

build.sbt, src/main/scala/fs2/kafka/KafkaConsumer.scala, src/main/scala/fs2/kafka/KafkaConsumerActor.scala, src/main/scala/fs2/kafka/internal/Synchronized.scala, src/main/scala/fs2/kafka/internal/syntax.scala, src/test/scala/fs2/kafka/internal/SynchronizedSpec.scala
Pull request #5 introduced an `MVar` for having exclusive access to the `Consumer`, which is necessary for being able to close the `Consumer` safely (avoiding `ConcurrentModificationException`) when using an `ExecutionContext` with more than one thread in `ConsumerSettings`. 
This pull request replaces `MVar` with a `Synchronization` primitive based on `Ref` and `Deferred`.
Massive thanks to @SystemFw for the help leading up to this.
=> Add Synchronization primitive for synchronized access

build.sbt, src/main/scala/fs2/kafka/CommitRecovery.scala, src/main/scala/fs2/kafka/CommitRecoveryException.scala, src/main/scala/fs2/kafka/ConsumerSettings.scala, src/main/scala/fs2/kafka/Jitter.scala, src/main/scala/fs2/kafka/KafkaConsumer.scala, src/main/scala/fs2/kafka/KafkaConsumerActor.scala, src/test/scala/fs2/kafka/CommitRecoverySpec.scala, src/test/scala/fs2/kafka/JitterSpec.scala
Add `CommitRecovery` for defining offset commit recovery strategies. The default strategy only retries `RetriableCommitFailedException` with a jittered exponential backoff for 10 attempts, switching to fixed rate retries for up to another 5 attempts (see `CommitRecovery#Default`).
You can override the `CommitRecovery` using `ConsumerSettings#withCommitRecovery`. If you would like to go back to default behaviour before this change (no retries), simply use `withCommitRecovery` with `CommitRecovery#None`.
=> Add support for offset commit recovery

build.sbt, src/main/scala/fs2/kafka/KafkaConsumer.scala, src/main/scala/fs2/kafka/KafkaConsumerActor.scala, src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
Add `KafkaConsumer#parallelPartitionedStream` for parallel processing per topic-partition. The main difference compared to `partitionedStream` is that we start individual streams per partition, which  get completed once the partition is revoked. When we get assigned a new partition, a new stream is started for that partition. This allows for parallel processing per topic-partition, where `partitionedStream` can only support parallel processing per topic-partition fetches.
---
Detailed changes to support this addition are listed below.
For `KafkaConsumer`:
- Add documentation for `KafkaConsumer` and provided functions.
- Change `partitionedStream` (and `stream`) to support faster interrupts.
- Fix `partitionedStream` (and `stream`) to support main fiber cancellation.
For …
=> Add KafkaConsumer#parallelPartitionedStream

src/main/scala/fs2/kafka/KafkaConsumerActor.scala, src/main/scala/fs2/kafka/internal/syntax.scala
This pull request attempts to fix #14 by explicitly creating new `Set`s in `KafkaConsumerActor`, instead of relying on `Map#keySet`, which uses a `DefaultKeySet` implementation. More specifically, we should now be avoiding the following code path, as seen at the top of the stack trace in the issue.
```
Exception in thread "fs2-kafka-consumer-20" java.lang.StackOverflowError
at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:505)
[...]
at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:507)
at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:507)
at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:507)
at scala.collection.MapLike$$anon$1.hasNext(MapLike.scala:186)
at scala.collection.Iterator.foreach(Iterator.scala:937)
at …
```
=> Explicitly create new Sets in KafkaConsumerActor

build.sbt, src/main/scala/fs2/kafka/KafkaConsumerActor.scala, src/main/scala/fs2/kafka/internal/syntax.scala, src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
This fixes the following `StackOverflowError` which occurs because we use `Map#filterKeys` which provides a lazy view, and over time we accumulate more and more of these views on the same `Map`, eventually resulting in a stack overflow. This pull request fixes the issue by using a strict version of `filterKeys` (and specialized `filterKeysStrictList` and `filterKeysStrictValuesList`).
Thanks to @sebastianvoss (https://github.com/ovotech/fs2-kafka/issues/14#issuecomment-438617692) for discovering and reporting this issue.
```
Exception in thread "fs2-kafka-consumer-20" java.lang.StackOverflowError
at scala.collection.MapLike$FilteredKeys.foreach(MapLike.scala:234)
at scala.collection.MapLike$FilteredKeys.foreach(MapLike.scala:234)
[...]
at …
```
=> Fix StackOverflowError in KafkaConsumer

build.sbt, src/main/scala/fs2/kafka/ConsumerFactory.scala, src/main/scala/fs2/kafka/ConsumerSettings.scala, src/main/scala/fs2/kafka/KafkaConsumer.scala, src/main/scala/fs2/kafka/KafkaProducer.scala, src/main/scala/fs2/kafka/ProducerFactory.scala, src/main/scala/fs2/kafka/ProducerSettings.scala
Add `ConsumerFactory` and `ProducerFactory`, along with:
- `ConsumerSettings#withConsumerFactory` and 
- `ProducerSettings#withProducerFactory`
for overriding how the `Consumer` and `Producer` are created, respectively.
This is mainly useful for testing purposes.
=> Change to allow overriding consumer and producer

build.sbt, src/main/scala/fs2/kafka/KafkaConsumerActor.scala
- Add State#withoutFetchesAndRecords to reduce number of `State#copy`s.
- Change to avoid `copy` in `State#asSubscribed` if already subscribed.
- Change to avoid creating `settings.pollTimeout.asJava` on every poll.
- Change to avoid creating the unused effect when storing new fetches.
=> Change to do less work in KafkaConsumerActor

build.sbt, src/main/scala/fs2/kafka/CommittableOffset.scala, src/main/scala/fs2/kafka/CommittableOffsetBatch.scala, src/main/scala/fs2/kafka/package.scala
- Add  internal `CommittableOffset#commitOffsets` with the offset commit function.
- Change `CommittableOffset#offsets` from `val` to `def`, as it's used less with these changes.
- Change `CommittableOffsetBatch#updated` to use `Map#updated` instead of creating a new `Map` for every offset with `CommittableOffset#offsets`.
- Change `CommittableOffsetBatch#fromFoldable` to avoid creating intermediate `CommittableOffsetBatch` instances.
- Add `CommittableOffsetBatch#fromFoldableOption` and use it in `commitBatchChunkOption`.
- Add documentation for `CommittableOffset` and `CommittableOffsetBatch`.
=> Change to improve performance of offset batching

src/main/scala/fs2/kafka/KafkaConsumerActor.scala, src/main/scala/fs2/kafka/internal/instances.scala
#21 changed to use `Chunk#vector` in `KafkaConsumerActor`. This pull request instead changes to use `Chunk#buffer`. Since we know the exact number of records we receive per partition, we can allocate an `Array` (via `ArrayBuffer`) to hold the records. We cannot directly use the `java.util.List` (wrapped in `Buffer`), because the `List` is wrapped with `java.util.Collections.unmodifiable`.
=> Change to use Chunk#buffer in KafkaConsumerActor

build.sbt, src/main/scala/fs2/kafka/ConsumerSettings.scala, src/main/scala/fs2/kafka/KafkaConsumerActor.scala, src/test/scala/fs2/kafka/BaseKafkaSpec.scala
Add `ConsumerSettings#withRecordMetadata`, which allows to specify a function for creating metadata for consumed records. Metadata will be included in `OffsetAndMetadata` for `CommittableOffset` (and in turn, `CommittableMessage`), and can then be committed together with the offsets. Just like before this change, there will be no metadata by default.
=> Add support for record metadata

src/main/scala/fs2/kafka/KafkaConsumer.scala, src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
#19 made `parallelPartitionedStream` an alias of `partitionedStream` for binary compatibility reasons, but we're now removing the alias as part of 0.17.0.
=> Remove KafkaConsumer#parallelPartitionedStream

src/main/scala/fs2/kafka/KafkaConsumer.scala, src/main/scala/fs2/kafka/KafkaProducer.scala
To be able to evolve `KafkaConsumer` and `KafkaProducer` without breaking binary compatibility.
=> Change to seal KafkaConsumer and KafkaProducer

docs/readme.md, src/main/scala/fs2/kafka/CommitRecoveryException.scala, src/main/scala/fs2/kafka/CommitTimeoutException.scala, src/main/scala/fs2/kafka/CommittableOffsetBatch.scala, src/main/scala/fs2/kafka/KafkaProducer.scala, src/main/scala/fs2/kafka/ProducerMessage.scala, src/main/scala/fs2/kafka/ProducerResult.scala, src/main/scala/fs2/kafka/internal/syntax.scala, src/test/scala/fs2/kafka/KafkaProducerSpec.scala
The previous encoding of `ProducerMessage` and `ProducerResult` had two limitations:
- `ProducerMessage#Multiple` could only support `List[ProducerRecord[K, V]]`, and
- due to their encodings, exhaustiveness checks could not be done for pattern matches.
The second limitation could be relaxed by changing the encoding slightly to use `final case class`es. This is not great from a binary compatibility perspective. However, if we want to relax the first limitation, we would have to parameterize by `F[_]`, and then pattern matching stops working due to type system limitations with GADTs.
Having to rely on pattern matching for `ProducerResult` is an annoyance for users. This pull request therefore introduces an alternative encoding of `ProducerMessage` and `ProducerResult` with a single case, …
=> Alternative Producer{Message,Result} encodings

src/main/scala/fs2/kafka/ConsumerSettings.scala, src/main/scala/fs2/kafka/package.scala
Add `consumerExecutionContextResource` and `consumerExecutionContextStream` with an option to specify the number of threads. This is mainly useful when running multiple `KafkaConsumer`s in the same application, at the same time.
=> Add support for setting number of ExecutionContext threads

docs/readme.md, src/main/scala/fs2/kafka/ProducerMessage.scala
When creating `ProducerMessage`s, type inference sometimes fails because there are multiple possible options for `F[_]` available. This especially happens when multiple cats instances are imported into scope. Without these, however, the type is correctly inferred as `Id`.
Here are some examples where `F[_]` cannot be inferred correctly.
```scala
import org.apache.kafka.clients.producer.ProducerRecord
import cats.implicits._
import fs2.kafka._
val record = new ProducerRecord("topic", "key", "value")
val passthrough = "passthrough"
ProducerMessage.single(record)
ProducerMessage.multiple(record)
ProducerMessage.passthrough(passthrough)
```
This pull request adds functions for partial type application, to explicitly specify `F[_]`.
```scala
import cats.Id
ProducerMessage.single[Id].of(record) …
```
=> Add ProducerMessage functions for partial type application

build.sbt, latestVersion.sbt, project/LatestVersion.scala
When checking binary-compatibility against previous releases, check all releases which should be binary-compatible, rather than just the latest release.
=> Change to check all binary-compatible releases

src/main/scala/fs2/kafka/AdminClientFactory.scala, src/main/scala/fs2/kafka/AdminClientSettings.scala, src/main/scala/fs2/kafka/KafkaAdminClient.scala, src/main/scala/fs2/kafka/internal/syntax.scala, src/main/scala/fs2/kafka/package.scala, src/test/scala/fs2/kafka/BaseKafkaSpec.scala, src/test/scala/fs2/kafka/KafkaAdminClientSpec.scala
This pull request adds an initial `KafkaAdminClient` which abstracts away the Java `AdminClient`, like the existing `KafkaConsumer` and `KafkaProducer`. Initially, not all operations from the Java client are supported. The following operations are currently supported, with more to be added as necessary.
- List consumer groups, consumer group offsets, and topics.
- Describe consumer groups and topics.
Following is an example of how to list all consumer groups and fetch their committed offsets.
```scala
import cats.effect.{ExitCode, IO, IOApp}
import cats.implicits._
import fs2.kafka._
object Main extends IOApp {
override def run(args: List[String]): IO[ExitCode] = {
val settings = AdminClientSettings.Default
.withBootstrapServers("localhost")
adminClientResource[IO](settings).use { client …
```
=> Add initial KafkaAdminClient

build.sbt, src/main/scala/fs2/kafka/ConsumerSettings.scala, src/main/scala/fs2/kafka/KafkaConsumer.scala, src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
- Add `withRequestTimeout` and `withDefaultApiTimeout` to `ConsumerSettings`.
- Add `beginningOffsets` and `endOffsets` to `KafkaConsumer`.
=> Add beginningOffsets and endOffsets

docs/quick-example.md, src/main/scala/fs2/kafka/ConsumerSettings.scala, src/main/scala/fs2/kafka/KafkaConsumer.scala, src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala
Add support for not explicitly having to specify an `ExecutionContext`.
If not specified, the default is `consumerExecutionContextResource(1)`.
=> Add support for default consumer ExecutionContext

docs/quick-example.md, src/main/scala/fs2/kafka/KafkaConsumer.scala, src/test/scala/fs2/kafka/KafkaAdminClientSpec.scala, src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
- Add `KafkaConsumer#subscribeTo` for subscribing to topics with varargs.
- Change `subscribe` to work for any `Reducible`, not only `NonEmptyList`.
- Change `subscribe`s to return `F[Unit]` instead of `Stream[F, Unit]`.
=> Add subscribeTo and generic subscribe

src/main/scala/fs2/kafka/CommitTimeoutException.scala, src/main/scala/fs2/kafka/NotSubscribedException.scala, src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
Since exceptions are mutable, we should not use a `case object` for `NotSubscribedException`.
=> Change to create new NotSubscribedException

src/main/scala/fs2/kafka/ConsumerShutdownException.scala, src/main/scala/fs2/kafka/KafkaConsumer.scala, src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala
- All `KafkaConsumer` requests now check to ensure the consumer has not already shutdown.
- All `KafkaConsumer` requests are now attempted, and errors returned in the returned effect.
- `KafkaConsumer#stream` and `partitionedStream` are now `def`s rather than `val`s.
=> Change to attempt KafkaConsumer requests

build.sbt, src/main/scala/fs2/kafka/KafkaConsumer.scala, src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
Hi, 
for our application we need to be able to set the offset from which to start reading. I found that the `seek` function exists in the Java client but is not exposed in this library.
=> Expose `seek` function in KafkaConsumer

src/main/scala/fs2/kafka/KafkaAdminClient.scala, src/main/scala/fs2/kafka/internal/instances.scala, src/test/scala/fs2/kafka/AdminClientSettingsSpec.scala, src/test/scala/fs2/kafka/BaseKafkaSpec.scala, src/test/scala/fs2/kafka/CommitTimeoutExceptionSpec.scala, src/test/scala/fs2/kafka/CommittableMessageSpec.scala, src/test/scala/fs2/kafka/CommittableOffsetBatchSpec.scala, src/test/scala/fs2/kafka/CommittableOffsetSpec.scala, src/test/scala/fs2/kafka/ConsumerSettingsSpec.scala, src/test/scala/fs2/kafka/ConsumerShutdownExceptionSpec.scala, src/test/scala/fs2/kafka/KafkaAdminClientSpec.scala, src/test/scala/fs2/kafka/KafkaConsumerSpec.scala, src/test/scala/fs2/kafka/KafkaProducerSpec.scala, src/test/scala/fs2/kafka/PackageSpec.scala, src/test/scala/fs2/kafka/ProducerMessageSpec.scala, src/test/scala/fs2/kafka/ProducerResultSpec.scala, src/test/scala/fs2/kafka/ProducerSettingsSpec.scala, src/test/scala/fs2/kafka/internal/SyntaxSpec.scala
Fixes `Show[ProducerRecord[K, V]]` when partition is `null`.
=> Add more tests for missing coverage

docs/src/main/mdoc/quick-example.md, src/main/scala/fs2/kafka/CommittableMessage.scala, src/main/scala/fs2/kafka/CommittableOffset.scala, src/main/scala/fs2/kafka/CommittableOffsetBatch.scala, src/main/scala/fs2/kafka/KafkaConsumer.scala, src/main/scala/fs2/kafka/package.scala, src/test/scala/fs2/kafka/KafkaAdminClientSpec.scala, src/test/scala/fs2/kafka/KafkaConsumerSpec.scala, src/test/scala/fs2/kafka/KafkaSpec.scala
`Sink` and `Stream#to` are deprecated in the next fs2 release.
Refer to https://github.com/functional-streams-for-scala/fs2/pull/1386 for more details.
=> Change to replace sinks with pipes

docs/src/main/mdoc/quick-example.md, src/main/scala/fs2/kafka/KafkaProducer.scala, src/main/scala/fs2/kafka/ProducerMessage.scala, src/main/scala/fs2/kafka/package.scala, src/test/scala/fs2/kafka/KafkaProducerSpec.scala, src/test/scala/fs2/kafka/ProducerMessageSpec.scala
#38 introduced an alternative encoding for `ProducerMessage`. It was a step in the right direction, but due to the `single`, `multiple`, and `passthrough` constructors, users might still be confused as to how messages should be created for their use cases. Additionally, type inference issues still exist, where sometimes the types of multiple `ProducerMessage`s have to be inferred and unified. Simply creating a message with a single record: `ProducerMessage.single(record)` can fail to infer `Id` as the context.
This pull request attempts to improve the situation by:
- removing the `ProducerMessage#single`, `multiple`, and `passthrough` constructors,
- adding `ProducerMessage#one` to always produce a single record (using `Id` as context),
- adding `ProducerMessage#apply` as a renamed …
=> Change KafkaProducer and ProducerMessage usage

docs/src/main/mdoc/quick-example.md, src/main/scala/fs2/kafka/Header.scala, src/main/scala/fs2/kafka/Headers.scala, src/main/scala/fs2/kafka/KafkaProducer.scala, src/main/scala/fs2/kafka/ProducerMessage.scala, src/main/scala/fs2/kafka/ProducerRecord.scala, src/main/scala/fs2/kafka/ProducerResult.scala, src/main/scala/fs2/kafka/internal/instances.scala, src/main/scala/fs2/kafka/package.scala, src/test/scala/fs2/kafka/CommittableMessageSpec.scala, src/test/scala/fs2/kafka/CommittableOffsetBatchSpec.scala, src/test/scala/fs2/kafka/CommittableOffsetSpec.scala, src/test/scala/fs2/kafka/HeaderSpec.scala, src/test/scala/fs2/kafka/HeadersSpec.scala, src/test/scala/fs2/kafka/JitterSpec.scala, src/test/scala/fs2/kafka/KafkaProducerSpec.scala, src/test/scala/fs2/kafka/ProducerMessageSpec.scala, src/test/scala/fs2/kafka/ProducerResultSpec.scala
#74 helped clarify how `ProducerMessage`s should be created and helped avoid some type inference and type unification issues. However, there are still some type inference issues present, mainly due to `ProducerMessage`'s type parameters being invariant. The reason for this is that `ProducerRecord`'s type parameters are invariant. 
For example, the following example still fails to compile.
```scala
// records: Stream[F, ProducerRecord[K, V]]
// passthrough: P
records
.map(ProducerMessage(record.some, none))
++ Stream(ProducerMessage(none, passthrough.some))
```
The changes in this pull request makes the above example compile. The changes introduce a custom implementation of `ProducerRecord` (and `Headers` and `Header`), which has covariant type parameters. We in turn change the …
=> Change to improve ProducerMessage type inference

src/main/scala/fs2/kafka/ConsumerSettings.scala, src/main/scala/fs2/kafka/KafkaConsumer.scala, src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, src/test/scala/fs2/kafka/ConsumerSettingsSpec.scala, src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
`partitionedStream.parJoinUnbounded` is essentially a more efficient version of the current `stream`, since it no longer couples fetch requests for different partitions, and enables prefetching of records.
=> Change KafkaConsumer#stream to alias of partitionedStream

build.sbt, src/main/scala/fs2/kafka/ConsumerSettings.scala, src/main/scala/fs2/kafka/KafkaConsumer.scala, src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, src/test/scala/fs2/kafka/ConsumerSettingsSpec.scala
This is an attempt to better document the backpressure in consumer streams. We add a new setting `maxPrefetchBatches` and corresponding setter `withMaxPrefetchBatches` to `ConsumerSettings`. An explanation of the backpressure and how this setting controls it is provided in the scaladoc.
Fixes #82.
=> Add ConsumerSettings#withMaxPrefetchBatches

build.sbt, docs/src/main/mdoc/quick-example.md, src/main/scala/fs2/kafka/ConsumerSettings.scala, src/main/scala/fs2/kafka/Deserializer.scala, src/main/scala/fs2/kafka/Header.scala, src/main/scala/fs2/kafka/HeaderDeserializer.scala, src/main/scala/fs2/kafka/HeaderSerializer.scala, src/main/scala/fs2/kafka/Headers.scala, src/main/scala/fs2/kafka/KafkaProducer.scala, src/main/scala/fs2/kafka/ProducerSettings.scala, src/main/scala/fs2/kafka/Serializer.scala, src/main/scala/fs2/kafka/internal/syntax.scala, src/main/scala/fs2/kafka/package.scala, src/test/scala/fs2/kafka/BaseCatsSpec.scala, src/test/scala/fs2/kafka/BaseGenerators.scala, src/test/scala/fs2/kafka/BaseKafkaSpec.scala, src/test/scala/fs2/kafka/BaseSpec.scala, src/test/scala/fs2/kafka/DeserializerSpec.scala, src/test/scala/fs2/kafka/HeaderDeserializerSpec.scala, src/test/scala/fs2/kafka/HeaderSerializerSpec.scala, src/test/scala/fs2/kafka/HeaderSpec.scala, src/test/scala/fs2/kafka/HeadersSpec.scala, src/test/scala/fs2/kafka/SerializerSpec.scala, src/test/scala/fs2/kafka/internal/SyntaxSpec.scala
For working with record headers, the following changes have been made.
- Add `HeaderDeserializer` for deserialization of record header values.
- Add `HeaderSerializer` for serializing values to use as header values.
- Add `Header.serialize` for serializing a value and creating a `Header`.
- Add `Header#headers` for creating a `Headers` with a single `Header`.
- Add `Header#as` and `attemptAs` for deserializing header values.
- Add `Headers#withKey` and alias `apply` for extracting a single `Header`.
- Add `Headers#concat` for concatenating another `Headers` instance.
- Add `Headers#asJava` for converting to Java Kafka-compatible headers.
- Add `Headers.fromIterable` to create `Headers` from `Iterable[Header]`.
- Add `Headers.fromSeq` to create `Headers` from `Seq[Header]`.
For record …
=> Change to improve serialization ergonomics

build.sbt, src/main/scala/fs2/kafka/KafkaAdminClient.scala, src/main/scala/fs2/kafka/internal/syntax.scala, src/test/scala/fs2/kafka/KafkaAdminClientSpec.scala
I'm hoping to use `fs2-kafka` in a new project at work, but I need these two operations. I tried to follow the existing patterns in the `KafkaAdminClient`, but please let me know if I should change anything!
=> Add 'describeCluster' and 'createTopic' operations to KafkaAdminClient.

build.sbt
=> Update Kafka client to 2.1.1

docs/src/main/mdoc/quick-example.md, src/main/scala/fs2/kafka/CommittableMessage.scala, src/main/scala/fs2/kafka/ConsumerRecord.scala, src/main/scala/fs2/kafka/ConsumerSettings.scala, src/main/scala/fs2/kafka/KafkaProducer.scala, src/main/scala/fs2/kafka/Timestamp.scala, src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, src/main/scala/fs2/kafka/internal/instances.scala, src/main/scala/fs2/kafka/package.scala, src/test/scala/fs2/kafka/CommittableMessageSpec.scala, src/test/scala/fs2/kafka/ConsumerRecordSpec.scala, src/test/scala/fs2/kafka/ConsumerSettingsSpec.scala, src/test/scala/fs2/kafka/ProducerResultSpec.scala, src/test/scala/fs2/kafka/TimestampSpec.scala
This pull request adds a custom `ConsumerRecord` similar to the existing Java Kafka `ConsumerRecord`. The custom record uses `fs2.kafka.Headers` and should generally be more nice to work with in Scala than the Java version.
=> Change to use custom ConsumerRecord

src/main/scala/fs2/kafka/Deserializer.scala, src/main/scala/fs2/kafka/HeaderDeserializer.scala
- Add `Deserializer.Attempt[A] = Deserializer[Either[Throwable, A]]`.
- Add `HeaderDeserializer.Attempt[A] = HeaderDeserializer[Either[Throwable, A]]`.
=> Add Attempt aliases for deserializers

build.sbt, src/main/scala/fs2/kafka/KafkaConsumer.scala, src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
- Add `KafkaConsumer#assignment`.
- Add `KafkaConsumer#position`.
- Add `KafkaConsumer#seekToBeginning`.
- Add `KafkaConsumer#seekToEnd`.
Fixes #92.
=> Add functions for working with consumer offsets

src/main/scala/fs2/kafka/Deserializer.scala, src/main/scala/fs2/kafka/HeaderDeserializer.scala, src/main/scala/fs2/kafka/HeaderSerializer.scala, src/main/scala/fs2/kafka/Serializer.scala, src/test/scala/fs2/kafka/DeserializerSpec.scala, src/test/scala/fs2/kafka/HeaderDeserializerSpec.scala, src/test/scala/fs2/kafka/HeaderSerializerSpec.scala, src/test/scala/fs2/kafka/SerializerSpec.scala
This pull request aims to make it easier to work with unkeyed records.
If all records are unkeyed, simply use `Unit` serializers and deserializers. These are available implicitly as `Serializer.unit` and `Deserializer.unit`, so you can use `ProducerSettings[Unit, V]` and `ConsumerSettings[Unit, V]`.
If some records are keyed and some are not, use `Serializer#option` and `Deserializer#option`, also available implicitly via `Serializer.option` and `Deserializer.option`. These serializers represent`None` as `null` in serialized form. Similarly, you can use these via `ProducerSettings[Option[K], V]` and `ConsumerSettings[Option[K], V]`.
For more complex types and cases, there is `Serializer.asNull[A]` and `Serializer.empty[A]` which serializes arbitrary values of a given type as `null` or the …
=> Change to improve working with unkeyed records

build.sbt, src/main/scala/fs2/kafka/KafkaConsumer.scala, src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala
Issue #105 describes a situation where the following happens.
1. Assignment of `x` happens, an `Assigned(x)` message is put on the Actor's queue.
2. An `Assignment` request is processed and returns `x` as current assignment.
This also registers a rebalance listener for assignments.
3. Streams are enqueued for the current assignment `x`.
4. The rebalance listener enqueues streams for assignment `x`.
Steps 3 and 4 can happen in reverse order, and there can be more assignments happening at the same time, but this covers the issue. The reason this happens is due to the fact that rebalance listeners simply queue messages onto the Actor's queue, rather than running the rebalance callbacks. This pull request changes to synchronously run the rebalance callbacks in the rebalance listener.
This …
=> Change to run rebalance callbacks during poll

src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala
In #106 we changed to run rebalance listeners as part of poll, but forgot to change to use the updated state after poll, and we were still relying on the previous state.
=> Change to use updated state after poll

src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala
This is mainly to reduce the amount of debug logs when pausing/resuming with an empty set of partitions.
=> Change to only pause/resume when necessary

src/main/scala/fs2/kafka/KafkaConsumer.scala, src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, src/main/scala/fs2/kafka/internal/LogEntry.scala, src/main/scala/fs2/kafka/internal/LogLevel.scala, src/main/scala/fs2/kafka/internal/Logging.scala, src/main/scala/fs2/kafka/internal/syntax.scala, src/test/resources/logback-test.xml
=> Add initial logging

build.sbt, src/main/scala/fs2/kafka/KafkaConsumer.scala
This is a WIP until I do more of them. I'm trying a function-per-commit so it's easier to see changes.
=> Improve readability of some functions by use for-comprehensions instead of nested `flatMap`

src/main/scala/fs2/kafka/ConsumerSettings.scala
The Java Kafka consumer defaults `auto.offset.reset` to `latest`, which can be surprising. We therefore set the default to `none`, which means an error will be raised if there are no offsets for the consumer group, and the user can then decide what the appropriate setting is for their use case.
=> Change default auto.offset.reset to none

src/main/scala/fs2/kafka/KafkaConsumer.scala, src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, src/main/scala/fs2/kafka/internal/WithConsumer.scala, src/main/scala/fs2/kafka/package.scala
- Add internal `WithConsumer` for using a Java Kafka `Consumer` in a thread-safe manner (using `Synchronized`)  and on a blocking `ExecutionContext`. This is effectively the same function as `KafkaConsumerActor#withConsumer`.
- Change to move all Java Kafka `Consumer` calls not requiring the actor's shared state from `KafkaConsumerActor` to `KafkaConsumer`, making use of `WithConsumer`.
=> Add internal WithConsumer construct

src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, src/main/scala/fs2/kafka/internal/LogEntry.scala
This pull request changes `KafkaConsumerActor` to not store records internally when records are received for partitions for which there are no requests. Instead, we change to `poll(Duration.Zero)` when there are no requests. This avoids assignment and records to be returned in one `poll`, which is the cause for 'records for partitions without requests'. This is also similar to what Alpakka Kafka does, which seems to have worked there. We add checks to make sure nothing unexpected is received.
=> Change to not store records internally in the actor

build.sbt, src/main/scala/fs2/kafka/CommittableOffset.scala, src/main/scala/fs2/kafka/CommittableOffsetBatch.scala, src/main/scala/fs2/kafka/CommittableProducerRecords.scala, src/main/scala/fs2/kafka/ConsumerGroupException.scala, src/main/scala/fs2/kafka/ConsumerSettings.scala, src/main/scala/fs2/kafka/IsolationLevel.scala, src/main/scala/fs2/kafka/KafkaConsumer.scala, src/main/scala/fs2/kafka/KafkaProducer.scala, src/main/scala/fs2/kafka/ProducerSettings.scala, src/main/scala/fs2/kafka/TransactionalKafkaProducer.scala, src/main/scala/fs2/kafka/TransactionalProducerMessage.scala, src/main/scala/fs2/kafka/TransactionalProducerResource.scala, src/main/scala/fs2/kafka/TransactionalProducerStream.scala, src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, src/main/scala/fs2/kafka/internal/WithConsumer.scala, src/main/scala/fs2/kafka/internal/WithProducer.scala, src/main/scala/fs2/kafka/package.scala, src/test/scala/fs2/kafka/BaseGenerators.scala, src/test/scala/fs2/kafka/BaseKafkaSpec.scala, src/test/scala/fs2/kafka/CommittableMessageSpec.scala, src/test/scala/fs2/kafka/CommittableOffsetBatchSpec.scala, src/test/scala/fs2/kafka/CommittableOffsetSpec.scala, src/test/scala/fs2/kafka/ConsumerSettingsSpec.scala, src/test/scala/fs2/kafka/IsolationLevelSpec.scala, src/test/scala/fs2/kafka/KafkaSpec.scala, src/test/scala/fs2/kafka/PackageSpec.scala, src/test/scala/fs2/kafka/ProducerSettingsSpec.scala, src/test/scala/fs2/kafka/TransactionalKafkaProducerSpec.scala, src/test/scala/fs2/kafka/TransactionalProducerMessageSpec.scala
Fixes #128.
Here's an implementation which (mostly) avoids touching existing classes. There's a bunch of code copy-pasted from the existing `KafkaProducer` and `ProducerMessage` which might be nice to consolidate 😄
=> Add new transactional producer

src/main/scala/fs2/kafka/ConsumerSettings.scala, src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, src/test/scala/fs2/kafka/ConsumerSettingsSpec.scala
Removed `ProducerSettings#shiftSerialization` in #130, so this is to do the same for `ConsumerSettings`.
=> Remove ConsumerSettings#shiftDeserialization

src/main/scala/fs2/kafka/ConsumerRecord.scala, src/main/scala/fs2/kafka/ConsumerSettings.scala, src/main/scala/fs2/kafka/KafkaProducer.scala, src/main/scala/fs2/kafka/ProducerSettings.scala, src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, src/main/scala/fs2/kafka/internal/WithConsumer.scala, src/main/scala/fs2/kafka/internal/WithProducer.scala, src/main/scala/fs2/kafka/package.scala, src/test/scala/fs2/kafka/ConsumerRecordSpec.scala
Exposes some existing type aliases for Java Kafka types. Some of these were already part of the public API, although the aliases themselves were private.
=> Change to expose Java Kafka type aliases

build.sbt, src/main/scala/fs2/kafka/Deserializer.scala, src/test/scala/fs2/kafka/BaseCatsSpec.scala, src/test/scala/fs2/kafka/BaseGenerators.scala, src/test/scala/fs2/kafka/ConsumerRecordSpec.scala, src/test/scala/fs2/kafka/DeserializerSpec.scala, src/test/scala/fs2/kafka/SerializerSpec.scala
`Deserializer`s become less surprising when used with `ConsumerSettings` if they require `F[_]` to be an effect type (since `ConsumerSettings` has the same requirement).
=> Change to require Sync for deserializers

src/main/scala/fs2/kafka/Serializer.scala, src/test/scala/fs2/kafka/BaseCatsSpec.scala, src/test/scala/fs2/kafka/BaseGenerators.scala, src/test/scala/fs2/kafka/DeserializerSpec.scala, src/test/scala/fs2/kafka/SerializerSpec.scala
Similarly to #135, this pull request changes to require `Sync` for `Serializer`s.
=> Change to require Sync for serializers

src/main/scala/fs2/kafka/AdminClientSettings.scala, src/main/scala/fs2/kafka/KafkaAdminClient.scala, src/main/scala/fs2/kafka/internal/WithAdminClient.scala, src/main/scala/fs2/kafka/package.scala, src/test/scala/fs2/kafka/AdminClientSettingsSpec.scala
The Java `KafkaAdminClient` relies on synchronization and can therefore block, so we should therefore shift to a blocking `ExecutionContext`. This also lets us run the blocking `close` function on a dedicated context.
=> Change KafkaAdminClient to use blocking ExecutionContext

build.sbt, src/main/scala/fs2/kafka/ConsumerSettings.scala, src/main/scala/fs2/kafka/KafkaConsumer.scala, src/main/scala/fs2/kafka/KafkaProducer.scala, src/main/scala/fs2/kafka/ProducerSettings.scala, src/main/scala/fs2/kafka/TransactionalKafkaProducer.scala, src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, src/main/scala/fs2/kafka/internal/OrElse.scala, src/test/scala/fs2/kafka/ConsumerSettingsSpec.scala, src/test/scala/fs2/kafka/ProducerSettingsSpec.scala, src/test/scala/fs2/kafka/SerializerSpec.scala
In some cases, serializers need a creation effect, i.e. `F[Deserializer[F, A]]` or `F[Serializer[F, A]]`. One example is the Confluent Avro serializer, which allocates mutable state as part of initialization. Typically, we want one instance per consumer or producer, which means we end up with code similar to the following.
```scala
import cats.effect.IO
import fs2.kafka._
val keyDeserializer = 
IO { println("key"); Deserializer[IO, Int] }
val valueDeserializer = 
IO { println("value"); Deserializer[IO, String] }
val settings: IO[ConsumerSettings[IO, Int, String]] =
keyDeserializer.flatMap { keyDeserializer =>
valueDeserializer.map { valueDeserializer =>
ConsumerSettings(
keyDeserializer = keyDeserializer,
valueDeserializer = valueDeserializer
)
}
}
```
This pull request changes …
=> Change to support creation effect for serializers

docs/src/main/mdoc/quick-example.md, modules/core/src/main/scala/fs2/kafka/CommittableConsumerRecord.scala, modules/core/src/main/scala/fs2/kafka/CommittableOffset.scala, modules/core/src/main/scala/fs2/kafka/CommittableOffsetBatch.scala, modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala, modules/core/src/main/scala/fs2/kafka/KafkaProducer.scala, modules/core/src/main/scala/fs2/kafka/ProducerSettings.scala, modules/core/src/main/scala/fs2/kafka/TransactionalKafkaProducer.scala, modules/core/src/main/scala/fs2/kafka/package.scala, modules/core/src/test/scala/fs2/kafka/KafkaAdminClientSpec.scala, modules/core/src/test/scala/fs2/kafka/KafkaConsumerSpec.scala, modules/core/src/test/scala/fs2/kafka/KafkaProducerSpec.scala, modules/core/src/test/scala/fs2/kafka/KafkaSpec.scala, modules/core/src/test/scala/fs2/kafka/TransactionalKafkaProducerSpec.scala
The fact that `KafkaProducer#produce` returns two effects (`F[F[ProducerResult[...]]]`) can be hard to understand and use correctly. To remedy the situation, we introduce a `produce` function, accepting `ProducerSettings`, which produces records in batches, and waits for them to finish sending. Batches are limited in size by `ProducerSettings#parallelism`.
Additionally, we remove most commit `Pipe`s and `producePassthrough`, since they are not really needed anymore, and some can result in poor performance if used incorrectly. We only leave the `commitBatchWithin` pipe for convenience.
=> Change to simplify produce and commit

modules/core/src/main/scala/fs2/kafka/CommittableOffset.scala, modules/core/src/main/scala/fs2/kafka/CommittableOffsetBatch.scala, modules/core/src/main/scala/fs2/kafka/ConsumerGroupException.scala, modules/core/src/main/scala/fs2/kafka/TransactionalKafkaProducer.scala, modules/core/src/test/scala/fs2/kafka/BaseGenerators.scala, modules/core/src/test/scala/fs2/kafka/CommittableConsumerRecordSpec.scala, modules/core/src/test/scala/fs2/kafka/CommittableOffsetBatchSpec.scala, modules/core/src/test/scala/fs2/kafka/CommittableOffsetSpec.scala, modules/core/src/test/scala/fs2/kafka/KafkaSpec.scala
Prevents committing offsets when records from multiple consumers with different group IDs are mixed together in the same `CommittableOffsetBatch`.
=> Prevent mixing consumer group ids

modules/core/src/main/scala/fs2/kafka/AdminClientSettings.scala, modules/core/src/main/scala/fs2/kafka/ConsumerSettings.scala, modules/core/src/main/scala/fs2/kafka/ProducerSettings.scala, modules/core/src/main/scala/fs2/kafka/internal/Blockers.scala, modules/core/src/main/scala/fs2/kafka/internal/WithAdminClient.scala, modules/core/src/main/scala/fs2/kafka/internal/WithConsumer.scala, modules/core/src/main/scala/fs2/kafka/internal/WithProducer.scala, modules/core/src/test/scala/fs2/kafka/AdminClientSettingsSpec.scala, modules/core/src/test/scala/fs2/kafka/ConsumerSettingsSpec.scala
This pull request replaces:
- `executionContext`, and
- `withExecutionContext(ExecutionContext)`
for `AdminClientSettings`, `ConsumerSettings`, and `ProducerSettings` with:
- `blocker`, and
- `withBlocker(Blocker)`.
=> Change to use Blocker over ExecutionContext

modules/core/src/main/scala/fs2/kafka/ConsumerSettings.scala, modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala, modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, modules/core/src/test/scala/fs2/kafka/ConsumerSettingsSpec.scala
The `pollInterval` and `pollTimeout` in `ConsumerSettings` control how often we should call `poll`, and for how long `poll` is allowed to block, respectively. The current behavior in `KafkaConsumer` does not necessarily respect these settings, as other requests are prioritzed before polling.
https://github.com/ovotech/fs2-kafka/blob/73710c1f98fe7e479c705359593020857813fb3d/modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala#L279-L282
Not only are other requests prioritized, but if there are no other outstanding requests, we wait for the next poll to happen, regardless whether other requests come in during that time. Essentially, we wait while we could handle other requests, and potentially don't respect `pollInterval`.
This pull request changes the behaviour to better respect …
=> Change to prioritize polls over other requests

modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, modules/core/src/main/scala/fs2/kafka/internal/LogEntry.scala
It seems the assumption made in #129 is incorrect: `poll(timeout)` with `timeout > 0` can both result in assignment and new records being returned for the new assignment. Therefore, we generally need to store records before fetch requests are received. This pull request effectively reverts #129.
=> Revert #129

docs/src/main/mdoc/transactions.md, modules/core/src/main/scala/fs2/kafka/TransactionalKafkaProducer.scala, modules/core/src/main/scala/fs2/kafka/TransactionalProducerResource.scala, modules/core/src/main/scala/fs2/kafka/TransactionalProducerSettings.scala, modules/core/src/main/scala/fs2/kafka/TransactionalProducerStream.scala, modules/core/src/main/scala/fs2/kafka/internal/Blockers.scala, modules/core/src/main/scala/fs2/kafka/internal/WithProducer.scala, modules/core/src/main/scala/fs2/kafka/package.scala, modules/core/src/test/scala/fs2/kafka/PackageSpec.scala, modules/core/src/test/scala/fs2/kafka/TransactionalKafkaProducerSpec.scala
Partially reverts #174, as proposed in https://github.com/ovotech/fs2-kafka/pull/182#issuecomment-525091340.
=> Revert complications in transactional producer & restore syntax.

docs/src/main/mdoc/producers.md, modules/core/src/main/scala/fs2/kafka/ProducerSettings.scala, modules/core/src/test/scala/fs2/kafka/TransactionalKafkaProducerSpec.scala
In Kafka 2.1, the default producer `max.retries` was changed to `Int.MaxValue`. This means records can be produced out-of-order. The blog post [Does Kafka really guarantee the order of messages?](https://blog.softwaremill.com/does-kafka-really-guarantee-the-order-of-messages-3ca849fd19d2) provides more detail on the topic. The fact that this change happened in a minor version can be surprising for people who missed [KIP-91](https://cwiki.apache.org/confluence/display/KAFKA/KIP-91+Provide+Intuitive+User+Timeouts+in+The+Producer) in the release notes.
The suggestion implemented by this pull request is to keep the old behaviour of `max.retries` set to `0`, so this new behaviour becomes opt-in, rather than on-by-default.
=> Change default max.retries to 0

modules/core/src/main/scala/fs2/kafka/ConsumerSettings.scala, modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala, modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, modules/core/src/test/scala/fs2/kafka/ConsumerSettingsSpec.scala
Reverts ovotech/fs2-kafka#180. It seems likely that the approach can result in cases where polls are always prioritized (either due to the scheduling, or because the Java consumer doesn't respect the timeout well enough).
=> Revert "Change to prioritize polls over other requests"

modules/vulcan/src/main/scala/fs2/kafka/vulcan/AvroDeserializer.scala, modules/vulcan/src/main/scala/fs2/kafka/vulcan/AvroSerializer.scala, modules/vulcan/src/test/scala/fs2/kafka/vulcan/AvroDeserializerSpec.scala, modules/vulcan/src/test/scala/fs2/kafka/vulcan/AvroSerializerSpec.scala
Particularly useful in IntelliJ, which will not auto-import the factory methods from the `fs2.kafka.vulcan` package object, creating temptation to import that object, which in turn breaks auto-import of anything from the root `vulcan` namespace.
=> Add `apply` methods for `AvroSerializer`/`AvroDeserializer`

docs/src/main/mdoc/modules.md, modules/core/src/main/scala/fs2/kafka/ConsumerSettings.scala, modules/core/src/main/scala/fs2/kafka/Deserializer.scala, modules/core/src/main/scala/fs2/kafka/ProducerSettings.scala, modules/core/src/main/scala/fs2/kafka/Serializer.scala, modules/core/src/main/scala/fs2/kafka/package.scala, modules/core/src/test/scala/fs2/kafka/ConsumerSettingsSpec.scala, modules/core/src/test/scala/fs2/kafka/DeserializerSpec.scala, modules/core/src/test/scala/fs2/kafka/ProducerSettingsSpec.scala, modules/core/src/test/scala/fs2/kafka/SerializerSpec.scala, modules/vulcan/src/main/scala/fs2/kafka/vulcan/AvroDeserializer.scala, modules/vulcan/src/main/scala/fs2/kafka/vulcan/AvroSerializer.scala
I've found the current naming confusing, both when learning the API and when explaining it to others: the default assumption for a newcomer is that `Deserializer.Record` is either a subtype of `Deserializer`, or a kind of record that is used in combination with one. It's also awkward to say "deserializer dot record" out loud.
I think this change improves the situation by presenting these types as first-class elements of the API.
=> Proposal to alias `Serializer.Record`/`Deserializer.Record` as `RecordSerializer`/`RecordDeserializer`

build.sbt, docs/src/main/mdoc/admin.md, modules/core/src/test/scala/fs2/kafka/BaseCatsSpec.scala, modules/core/src/test/scala/fs2/kafka/KafkaAdminClientSpec.scala, modules/core/src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
This pull request updates:
- Confluent serializer to 5.4.0,
- Kafka to 2.4.0,
- Embedded Kafka to 2.4.0,
- Vulcan to 0.3.1,
and re-enables all tests on Scala 2.13. Mima reporting is disabled in preparation of the 1.0 release.
=> Update Kafka to 2.4.0

modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, modules/core/src/main/scala/fs2/kafka/internal/LogEntry.scala
When rebalance revokes partitions for which there are no fetch requests, we should remove any buffered records for the partition. This should help with duplicate records being processed due to rebalances (the next consumer for the partition will refetch these records).
=> Change to ensure revoked partition records are removed

modules/core/src/main/scala/fs2/kafka/ProducerSettings.scala
Similarly to https://github.com/akka/alpakka-kafka/issues/909, we should increase the default significantly to allow `send` to block/backpressure on the internal `Blocker` instance.
=> Change default ProducerSettings#parallelism to 10000

docs/src/main/mdoc/consumers.md, docs/src/main/mdoc/modules.md, docs/src/main/mdoc/producers.md, docs/src/main/mdoc/quick-example.md, docs/src/main/mdoc/transactions.md
The `KafkaConsumer` and `KafkaProducer` classes require a url with a port.
If the port is not provided then an exception will be thrown - example stacktrace is below
```
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820)
at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:631)
at fs2.kafka.ConsumerSettings$.$anonfun$create$3(ConsumerSettings.scala:567)
at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
at cats.effect.internals.IORunLoop$RestartCallback.run(IORunLoop.scala:366)
at cats.effect.internals.Trampoline.cats$effect$internals$Trampol …
```
=> Update documentation: Add port to bootstrap server url.

build.sbt, modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala, modules/core/src/main/scala/fs2/kafka/internal/LogEntry.scala, modules/core/src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
I added `partitionsMapStream: Stream[F, Map[TopicPartition, Stream[F, CommittableConsumerRecord[F, K, V]]]]` method to a `KafkaConsumer`.
This will be the most generic version across all stream methods on the `KafkaConsumer`. It reflects the Kafka rebalance process. With each rebalance Kafka revoke all partitions and after that assign all new partitions at once. In `partitionsMapStream` each element will be this assignment with the newly assigned partitions and it's corresponding streams. All other `stream` methods in my branch are based on `partitionsMapStream`.
Implementation was pretty simple because the old `partitionedStream` implementation contains all needed information. I just exposed all these details about partitions and assignments in the public API.
I believe, that …
=> Partitions map stream

build.sbt, modules/core/src/main/scala/fs2/kafka/KafkaAdminClient.scala, modules/core/src/test/scala/fs2/kafka/KafkaAdminClientSpec.scala
I added new methods to the KafkaAdminClient: `alterConsumerGroupOffsets` and `deleteConsumerGroupOffsets`. Also, I updated kafka version to 2.6.0.
=> Added KafkaAdminClient methods alterConsumerGroupOffsets and deleteConsumerGroupOffsets

build.sbt
I ran into a `NoSuchMethodError` in the FS2 runtime regarding `Chain.traverse` into `Seq`, and building this project locally with Cats 2.2.0 seemed to fix the issue. FS2 and Cats Effect are both depending on Cats 2.2.0, while this project depends on 2.1.1 directly. 
I'm not sure if there are other implications of making this change.
=> Bump Cats to 2.2.0

docs/src/main/mdoc/producers.md, modules/core/src/main/scala/fs2/kafka/KafkaProducer.scala, modules/core/src/main/scala/fs2/kafka/ProducerResource.scala, modules/core/src/main/scala/fs2/kafka/ProducerStream.scala, modules/core/src/main/scala/fs2/kafka/package.scala, modules/core/src/test/scala/fs2/kafka/KafkaProducerSpec.scala, modules/core/src/test/scala/fs2/kafka/PackageSpec.scala
I think methods on companion objects are more idiomatic in Scala - they're also more discoverable, especially with autocompletion tooling. I'd be inclined to deprecate the package object methods and remove them in v2 - thoughts?
=> Improve ergonomics of instantiating producers

build.sbt, modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala, modules/core/src/main/scala/fs2/kafka/consumer/KafkaCommit.scala, modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, modules/core/src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
I added `commitSync` and` commitAsync` methods. I decided to add both methods (not just `commitAsync`) because they have slightly different semantics. For example, `commitAsync` is based on` poll` calls, but `commitSync` not.
I also added tests for these methods. I managed to reuse the existed test code for this.
=> Added commitSync and commitAsync methods to the KafkaConsumer

.github/workflows/notes.yml
Unfortunately, release-drafter doesn't seem to work well with multi-branch workflows.
=> Only draft releases for series/1.x

modules/core/src/main/scala/fs2/kafka/package.scala
noticed that the deprecation warning didn't match what change was required to fix it
=> correct deprecation message for adminClientStream

.github/workflows/ci.yml, build.sbt, modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala, modules/core/src/main/scala/fs2/kafka/consumer/KafkaConsumerLifecycle.scala
I made a bincompat mistake with #504 - this fixes it by providing a default implementation of the new methods in `KafkaConsumerLifecycle`
=> Fix consumer lifecycle bincompat

docs/src/main/mdoc/consumers.md, docs/src/main/mdoc/producers.md, modules/core/src/main/scala/fs2/kafka/ConsumerRecord.scala, modules/core/src/main/scala/fs2/kafka/ConsumerSettings.scala, modules/core/src/main/scala/fs2/kafka/Deserializer.scala, modules/core/src/main/scala/fs2/kafka/HeaderDeserializer.scala, modules/core/src/main/scala/fs2/kafka/HeaderSerializer.scala, modules/core/src/main/scala/fs2/kafka/Headers.scala, modules/core/src/main/scala/fs2/kafka/KafkaProducer.scala, modules/core/src/main/scala/fs2/kafka/ProducerSettings.scala, modules/core/src/main/scala/fs2/kafka/Serializer.scala, modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, modules/core/src/main/scala/fs2/kafka/internal/WithConsumer.scala, modules/core/src/main/scala/fs2/kafka/internal/WithProducer.scala, modules/core/src/main/scala/fs2/kafka/internal/syntax.scala, modules/core/src/main/scala/fs2/kafka/package.scala, modules/core/src/test/scala/fs2/kafka/BaseKafkaSpec.scala, modules/core/src/test/scala/fs2/kafka/ConsumerRecordSpec.scala, modules/core/src/test/scala/fs2/kafka/SerializerSpec.scala, modules/core/src/test/scala/fs2/kafka/internal/SyntaxSpec.scala
I'm reverting this until we decide about possible package reorganization in #502, so we don't create new aliases that then need to be deprecated.
Reverts fd4s/fs2-kafka#474
=> Revert "Rename `KafkaX` type aliases to `JavaX`"

modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala, modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, modules/core/src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
This is a fix for #532
Some words about expected behavior. fs2 is a pull-based library: stream will not push the new step until the previous step is completed. So, if we have a `flatMap` on a stream, the next step will be executed only when the current inner stream completes. Projecting this onto our situation, if we have a code like this: 
```scala
consumer.partitionsMapStream.flatMap { assignment =>
val innerStream = handle(assignment)
innerStream
} 
```
the next assignment will be received only when the `innerStream` finished. If `innerStream` is based on partition streams from the `assignment`, it will automatically work: on rebalance, old streams are finished, and `innerStream` is finished too. And this is the expected behavior.
But sometimes not all old partition streams finished. …
=> Rebalance doesn't work reliably fix

modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala, modules/core/src/main/scala/fs2/kafka/KafkaProducer.scala, modules/core/src/main/scala/fs2/kafka/KafkaProducerConnection.scala, modules/core/src/main/scala/fs2/kafka/TransactionalKafkaProducer.scala, modules/core/src/test/scala/fs2/kafka/KafkaConsumerSpec.scala, modules/core/src/test/scala/fs2/kafka/KafkaProducerSpec.scala, modules/core/src/test/scala/fs2/kafka/TransactionalKafkaProducerSpec.scala
ScalaFix to follow. Resolves #571
=> More idiomatic syntax for instantiating things via partial application

docs/src/main/mdoc/admin.md, modules/core/src/main/scala/fs2/kafka/AdminClientSettings.scala, modules/core/src/main/scala/fs2/kafka/ConsumerSettings.scala, modules/core/src/main/scala/fs2/kafka/KafkaAdminClient.scala, modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala, modules/core/src/main/scala/fs2/kafka/KafkaProducer.scala, modules/core/src/main/scala/fs2/kafka/KafkaProducerConnection.scala, modules/core/src/main/scala/fs2/kafka/ProducerSettings.scala, modules/core/src/main/scala/fs2/kafka/TransactionalKafkaProducer.scala, modules/core/src/main/scala/fs2/kafka/admin/MkAdminClient.scala, modules/core/src/main/scala/fs2/kafka/consumer/MkConsumer.scala, modules/core/src/main/scala/fs2/kafka/internal/WithAdminClient.scala, modules/core/src/main/scala/fs2/kafka/internal/WithConsumer.scala, modules/core/src/main/scala/fs2/kafka/internal/WithProducer.scala, modules/core/src/main/scala/fs2/kafka/producer/MkProducer.scala, modules/core/src/test/scala/fs2/kafka/AdminClientSettingsSpec.scala, modules/core/src/test/scala/fs2/kafka/BaseKafkaSpec.scala, modules/core/src/test/scala/fs2/kafka/ConsumerSettingsSpec.scala, modules/core/src/test/scala/fs2/kafka/ProducerSettingsSpec.scala, modules/core/src/test/scala/fs2/kafka/TransactionalKafkaProducerSpec.scala
This is binary-breaking but mostly source-compatible, so it seems worth doing before 2.0.0 given it's likely to be needed for #553.
=> Decouple resource instantiation from settings

modules/core/src/main/scala/fs2/kafka/KafkaAdminClient.scala, modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala, modules/core/src/main/scala/fs2/kafka/KafkaProducer.scala, modules/core/src/main/scala/fs2/kafka/KafkaProducerConnection.scala, modules/core/src/main/scala/fs2/kafka/TransactionalKafkaProducer.scala
I'm not 100% happy with the added boilerplate, or with it being needed, but I don't have a better idea. Any thoughts?
=> Add missing MkProducer argument, force compiler errors when they're missing

modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, modules/core/src/main/scala/fs2/kafka/internal/WithConsumer.scala
It seems the use of semaphore was only needed because `commitAsync` was running on the compute pool rather than the consumer blocker. Although it's non-blocking, the initial invocation is supposed to run on the same thread as other consumer operations.
=> Use blocker for scheduling commitAsync, remove semaphore from WithConsumer

modules/core/src/main/scala/fs2/kafka/consumer/MkConsumer.scala, modules/core/src/main/scala/fs2/kafka/producer/MkProducer.scala, modules/core/src/test/scala/fs2/kafka/TransactionalKafkaProducerSpec.scala
This will be needed for #553, since creating (e.g.) `Resource[F, KafkaProducer[G, K, V]]` will require `MkProducer[F]` but `Producersettings[G, K, V]`.
=> Decouple type params of `MkX` traits from type param of settings 

modules/core/src/main/scala/fs2/kafka/KafkaProducer.scala, modules/core/src/main/scala/fs2/kafka/KafkaProducerConnection.scala, modules/core/src/main/scala/fs2/kafka/TransactionalKafkaProducer.scala
Something like this will be needed for #553, since Dispatcher is allocated as `Resource[F, Dispatcher[F]]`. This change also removes a potential performance bottleneck (since Dispatcher does everything on a single fiber), and a potential source of bugs around Dispatcher lifecycle (it cancels running fibers when the resource is released - I've seen some error logs in tests relating to this, though I couldn't track down the cause.)
=> Replace Deferred with Promise in KafkaProducer, remove Dispatcher

modules/core/src/main/scala/fs2/kafka/ConsumerSettings.scala, modules/core/src/test/scala/fs2/kafka/ConsumerSettingsSpec.scala
=> Update doc of ConsumerSettings#withBlocker

modules/core/src/main/scala/fs2/kafka/ConsumerSettings.scala, modules/core/src/main/scala/fs2/kafka/ProducerSettings.scala, modules/core/src/main/scala/fs2/kafka/internal/Blocking.scala, modules/core/src/main/scala/fs2/kafka/internal/WithConsumer.scala, modules/core/src/main/scala/fs2/kafka/internal/WithProducer.scala, modules/core/src/test/scala/fs2/kafka/ConsumerSettingsSpec.scala, modules/core/src/test/scala/fs2/kafka/ProducerSettingsSpec.scala
I haven't done this for `AdminClient`, as the only blocking operation we do on `AdminClient` is `close`. However if anyone strongly thinks we should provide it for consistency then I'm open to that.
Resolves #589
=> Allow use of custom blocking context for `Consumer` and `Producer`

modules/core/src/main/scala/fs2/kafka/TransactionalKafkaProducer.scala, modules/core/src/main/scala/fs2/kafka/TransactionalProducerResource.scala, modules/core/src/main/scala/fs2/kafka/TransactionalProducerStream.scala, modules/core/src/test/scala/fs2/kafka/TransactionalKafkaProducerSpec.scala
Similar to consumer and producer metrics, expose underlying java client metrics.
=> Add transactional producer metrics

modules/core/src/main/scala/fs2/kafka/KafkaProducer.scala, modules/core/src/test/scala/fs2/kafka/KafkaProducerSpec.scala
Per suggestions in #446 
Tests are def a bit anaemic, wasn't sure what the right balance between exhaustivity and maintainability was.
Didn't include a `pipe` method as suggested in the original issue as was not clear what the semantics should be (flatten the `F[F[...]]`?), but happy to add if clarified.
=> Add producer convenience methods

docs/src/main/mdoc/consumers.md, docs/src/main/mdoc/producers.md, docs/src/main/mdoc/quick-example.md, modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala, modules/core/src/main/scala/fs2/kafka/consumer/KafkaConsume.scala, modules/core/src/test/scala/fs2/kafka/KafkaAdminClientSpec.scala, modules/core/src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
I think this improves clarity, especially with the extension methods on allocating streams. I'd like to get this in for the next release, as having two uses of `.stream` with totally different meanings looks weird to me.
I don't see why we can't do this in the 1.x/2.x series - we can consider later whether we want to deprecate `stream` at some time in the future.
=> Alias `stream` as `records`

README.md
This should reduce confusion in choosing a version. It mentions major versions only to avoid the need for frequent manual updates.
=> Add a basic version matrix to the readme

modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala, modules/core/src/main/scala/fs2/kafka/consumer/KafkaConsume.scala, modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, modules/core/src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
KafkaConsumer.partitionsMapStream would drop all partition streams
whenever a partition revocation was advertised, but would only create
streams for newly assigned partitions. This worked fine with the default
assignor, which revokes all existing assignments before new assignments
are issued during a rebalance operation.
The CooperativeStickyAssignor, attempts to keep assignments stable,
performing rebalance operations in two steps: on a first pass a minimal
set of assignments are revoked, these are then redistributed to balance
the consumer cluster.
In order to support this assignor, the consumer needs to keep track of
the current set of assignments and, in the case of partitionsMapStream,
recreate partition streams for partitions that were kept. While the
underlying …
=> Add support for using CooperativeStickyAssignor with KafkaConsumer

.scala-steward.conf, build.sbt
Make scala-steward less noisy for 1.x series. Also, I pinned cats-effect and fs2 versions to 2.x.
=> Improve scala-steward config for 1.x series

modules/core/src/main/scala/fs2/kafka/TransactionalKafkaProducer.scala, modules/core/src/main/scala/fs2/kafka/internal/WithProducer.scala, modules/core/src/main/scala/fs2/kafka/internal/WithTransactionalProducer.scala, modules/core/src/main/scala/fs2/kafka/internal/package.scala, modules/core/src/test/scala/fs2/kafka/TransactionalKafkaProducerSpec.scala
Addresses a bug with concurrent transactional producer access discovered in #883.
Introduces a semaphore around the transactional produce `WithProducer` implementation. This is because only one transaction may be started per producer at any one time, so produce requests must be queued.
=> Threadsafe transactions

docs/src/main/mdoc/transactions.md
Relates to #888, will need to wait for it to be ported to `series/2.x`
Adds note on concurrent access performance constraints.
=> Update transactional producer docs

modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala, modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, modules/core/src/main/scala/fs2/kafka/internal/LogEntry.scala, modules/core/src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
Postpones deserialising records until they are pushed onto a consumer stream, reducing the complexity of `KafkaConsumerActor`.
This means that a deserialization error in a partitioned stream will cause only the specific partition stream to fail, rather than crash the actor - I think that's a good thing, but maybe we should reproduce the existing behaviour (with a configurable toggle) in the 2.x series?
=> Move deserialization from KafkaConsumerActor to KafkaConsumer

build.sbt, modules/core/src/main/scala/fs2/kafka/KafkaProducer.scala, modules/core/src/main/scala/fs2/kafka/KafkaProducerConnection.scala, modules/core/src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
Makes some incremental progress on #572
=> Add `produce` method to `KafkaProducerConnection`

modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala, modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala
This was supposed to be a demo but I got a bit carried away - inspired by #903
=> Use semaphore-like permits for some actor operations

build.sbt, modules/core/src/test/resources/logback-test.xml, modules/core/src/test/scala/fs2/kafka/BaseKafkaSpec.scala
Also adds support for running tests on Arm64
=> Update testcontainers version, set image name and version explicitly

modules/core/src/test/scala/fs2/kafka/BaseKafkaSpec.scala, modules/core/src/test/scala/fs2/kafka/KafkaAdminClientSpec.scala, modules/core/src/test/scala/fs2/kafka/KafkaConsumerSpec.scala, modules/core/src/test/scala/fs2/kafka/TransactionalKafkaProducerSpec.scala
Reduces CI time from ~16m to ~9m. Also opens the way for further huge speedup by paralellizing with [weaver-test](https://disneystreaming.github.io/weaver-test/).
=> Use a shared test container for each suite

build.sbt, modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala, modules/core/src/main/scala/fs2/kafka/consumer/KafkaOffsets.scala, modules/core/src/main/scala/fs2/kafka/consumer/KafkaOffsetsV2.scala, modules/core/src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
New methods added to `trait KafkaOffsets[F[_]]`:
```
def committed(partitions: Set[TopicPartition]): F[Map[TopicPartition, OffsetAndMetadata]]
def committed(partitions: Set[TopicPartition], timeout: FiniteDuration): F[Map[TopicPartition, OffsetAndMetadata]]
```
=> Additional consumer functionality exposed

.github/workflows/ci.yml, build.sbt, modules/vulcan/src/main/scala-3/kafka.util/VerifiableProperties.scala, modules/vulcan/src/main/scala/fs2/kafka/vulcan/AvroSerializer.scala, modules/vulcan/src/main/scala/fs2/kafka/vulcan/AvroSettings.scala, modules/vulcan/src/test/scala/fs2/kafka/vulcan/AvroSerializerSpec.scala, modules/vulcan/src/test/scala/fs2/kafka/vulcan/AvroSettingsSpec.scala, modules/vulcan/src/test/scala/fs2/kafka/vulcan/PackageSpec.scala
Resolves #689 and a major motivation for #506. Overrides the entrypoint to `KafkaAvroSerializer` to use the actual writer schema rather than guessing it from the intermediate Java representation.
=> Fix auto-registration of Avro union (etc) types

.gitignore, docs/src/main/mdoc/consumers.md
The methods `commitBatch` and `commitBatchOption` were removed by this PR: https://github.com/fd4s/fs2-kafka/pull/146
=> Removing references to `commitBatch` and `commitBatchOption` in Documentation

modules/core/src/test/scala/fs2/kafka/internal/SyntaxSpec.scala
This fixes the test failure on the 3.x branch.
=> Refactor future cancellation test to avoid dependence on KakfaFuture internals

modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala, modules/core/src/main/scala/fs2/kafka/consumer/KafkaConsume.scala, modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, modules/core/src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
Add backport of CooperativeStickyAssignor support in KafkaConsumer from https://github.com/fd4s/fs2-kafka/pull/844 to `1.x`
=> Add support for CooperativeStickyAssignor with KafkaConsumer on 1.x

modules/core/src/main/scala/fs2/kafka/TransactionalKafkaProducer.scala, modules/core/src/test/scala/fs2/kafka/TransactionalKafkaProducerSpec.scala
Fix produce method of TransactionalKafkaProducer, when method is invoked with empty records and not empty offsets. Offsets will be committed.
Closes issue https://github.com/fd4s/fs2-kafka/issues/1099
=> 1099 Fix produce method of TransactionalKafkaProducer, when method is invoked with empty records and non-empty offsets

modules/core/src/main/scala/fs2/kafka/TransactionalKafkaProducer.scala
This is an extremely minor change that should have no/minimal end-user impact, but is probably more "correct" and may avoid invalid states in the producer.
Currently, we do not wait for the underlying Kafka producer to have sent any records before attempting to close (commit or abort) the transaction. Instead, it only waits until the records have been buffered internally. This works because `commitTransaction` awaits outstanding records and rethrows in the case of failure; if any record fails to send `commitTransaction` will fail and the user will see that.
With this change we will only try to commit the transaction once all records have been received by Kafka. This should have no user-facing impact in most cases. But, it may mean we more correctly call `abortTransaction` if a record …
=> Change transactional producer to await produce before ending transaction

build.sbt, modules/core/src/main/scala/fs2/kafka/RecordDeserializer.scala, modules/core/src/main/scala/fs2/kafka/RecordSerializer.scala, modules/core/src/test/scala/fs2/kafka/RecordDeserializerSpec.scala, modules/core/src/test/scala/fs2/kafka/RecordSerializerSpec.scala
Unfortunately, porting the `transform` method on `RecordSerializer`/`RecordDeserializer` forward requires a cast now that serdes are typed for key vs value. I don't think this is going to break anything but I'm not terribly comfortable with it either - it could be an extra incentive to improve these abstractions, but for now I want to push forward towards a 3.0 release given the library has been neglected for many months.
=> Merge 2.x into 3.x

.github/workflows/ci.yml, build.sbt
This reverts commit 78fc4258c8df82919d8ae38f6221dc4b6318915c.
@vlovgr what was the purpose of this change? I'm reverting it now to publish v2.6 but we can change it again if needed.
=> Revert "Change to publish on series branches"

build.sbt, modules/core/src/main/scala/fs2/kafka/KafkaProducer.scala, modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, modules/core/src/main/scala/fs2/kafka/internal/WithAdminClient.scala, modules/core/src/main/scala/fs2/kafka/internal/syntax.scala, modules/core/src/test/scala/fs2/kafka/internal/SyntaxSpec.scala
Resolves #1181 by returning `Some(F.unit)` instead of `None` for the canceler of the uncancelable async commit operation.
Also uses configured timeout for sync commit, and renames some syntax to avoid clashing with a new method on `IO` in forthcoming CE3.5
=> Preparatory changes for new CE cancelation semantics

.github/workflows/ci.yml, .scala-steward.conf, build.sbt, modules/core/src/main/scala/fs2/kafka/CommittableProducerRecords.scala, modules/core/src/main/scala/fs2/kafka/KafkaProducer.scala, modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, modules/core/src/main/scala/fs2/kafka/package.scala, modules/core/src/test/scala/fs2/kafka/KafkaProducerSpec.scala, modules/core/src/test/scala/fs2/kafka/KafkaSpec.scala, modules/core/src/test/scala/fs2/kafka/TransactionalKafkaProducerSpec.scala
Fixes #1234.
**NOTE:** I had to bump Scala 3 lib because [since 3.8.0](https://github.com/typelevel/fs2/releases/tag/v3.8.0) fs2 uses 3.3.x
=> Bump CE and fs2 to the latest version

docs/src/main/mdoc/transactions.md
The transaction example in the docs is outdated and doesn't cover creating partition unique transaction id. 
I've updated the example and changed the docs.
=> Updated transaction docs

.scala-steward.conf, build.sbt
Make Scala Steward great again now that 2.x is EOL ❤️‍🔥
=> scala-steward (3.x series): reenable ignored 2.x series dependencies

docs/src/main/mdoc/consumers.md, docs/src/main/scala/fs2/kafka/docs/Main.scala
```
[error] /home/runner/work/fs2-kafka/fs2-kafka/docs/src/main/scala/fs2/kafka/docs/Main.scala:12:47: match may not be exhaustive.
[error]     val Array(major, minor, _) = version.split('.')
[error]                                               ^
[error] /home/runner/work/fs2-kafka/fs2-kafka/docs/src/main/scala/fs2/kafka/docs/Main.scala:17:43: match may not be exhaustive.
[error]     val Array(major, _, _) = version.split('.')
[error]                                           ^
[error] two errors found
[error] (docs / Compile / compileIncremental) Compilation failed
[error] Total time: 10 s, completed Oct 1, 2023 7:48:53 AM
```
=> Fix docs publishing

modules/vulcan-testkit-munit/src/main/scala/fs2/kafka/vulcan/testkit/SchemaSuite.scala
Expose compatibility checker creation for use compositionally 
for example
```scala
val loadSchemaRegistrySettings: IO[SchemaRegistryClientSettings[IO]] = ???
val checker = ResourceSuiteLocalFixture(
"my-fixture",
Resource.eval(loadSchemaRegistrySettings.flatMap(newCompatibilityChecker(_)))
)
```
=> Expose creation of compat checker

modules/core/src/test/scala/fs2/kafka/internal/SyntaxSpec.scala, modules/vulcan-testkit-munit/src/main/scala/fs2/kafka/vulcan/testkit/SchemaSuite.scala
- After merging #988 format was wrong
- `SyntaxSpec` is still flaky, thus I've changed the way we check cancellation by using `CountDownLatch`
=> Fix CI build issues

docs/src/main/mdoc/modules.md, modules/vulcan-testkit-munit/src/main/scala/fs2/kafka/vulcan/testkit/SchemaSuite.scala
Credit to @thatfulvioguy for the incompatibility rendering code for the clues.
=> Add compatiblity assertions with clues

build.sbt, modules/core/src/main/scala/fs2/kafka/AdminClientSettings.scala, modules/core/src/main/scala/fs2/kafka/package.scala, modules/vulcan/src/main/scala/fs2/kafka/vulcan/AvroSettings.scala
It's been a long time since 3.x was published and users have had enough time to stop using these deprecated methods.
=> Remove deprecated methods

modules/core/src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
There's no need to consume a topic's records in order to test the partition assignments.
This causes a race condition where, if `consumer.records` occurs first, the initial expected empty assignment is not streamed 👇🏽 (see the missing first `TreeSet()`):
```
[info] - should stream assignment updates to listeners *** FAILED *** (10 seconds, 632 milliseconds)
[info]   List(TreeSet(topic-2b357246-81b5-460d-ba2e-822ed148e635-0, topic-2b357246-81b5-460d-ba2e-822ed148e635-1, topic-2b357246-81b5-460d-ba2e-822ed148e635-2), TreeSet(), TreeSet(topic-2b357246-81b5-460d-ba2e-822ed148e635-0, topic-2b357246-81b5-460d-ba2e-822ed148e635-1)) had length 3 instead of expected length 4 (KafkaConsumerSpec.scala:803)
```
=> Fix flaky `KafkaConsumer#assignmentStream` tests

docs/src/main/mdoc/consumers.md, docs/src/main/mdoc/quick-example.md, modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala, modules/core/src/main/scala/fs2/kafka/consumer/KafkaConsumeChunk.scala, modules/core/src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
This adds an API to make the pattern of chunk-based consumers a first-class concept. The idea keeps popping up in the typelevel discord, and we've been successfully using it at $WORK for a while now, so it makes sense to add it.
The pattern aims at helping users to implement consumers without auto-commit to write their code without having to do too much work in order to achieve correct offset committing (no offsets must be lost, offsets should be committed only after messages have been processed, etc).
It achieves that by switching from processing messages in a `Stream[F, CommittableConsumerRecord[F, K, V]]` to processing them chunks: `Chunk[ConsumerRecord[K, V]] => F[Unit]`. After each chunk, the offsets of the chunk are committed.
This has a couple of advantages (summarizing [what Fabio …
=> Add chunk-based consumer API

.github/workflows/ci.yml, build.sbt, project/plugins.sbt
Latest `mdoc` is compiled with JDK 11 but our GHA publish job was configured to use JDK 8:
```
[info] running fs2.kafka.docs.Main 
Error: Exception in thread "sbt-bg-threads-1" java.lang.UnsupportedClassVersionError: mdoc/MainSettings$ has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```
👆🏽 See [this run log](https://github.com/fd4s/fs2-kafka/actions/runs/7150982561/job/19474915886) for the full error.
By switching the order of `githubWorkflowJavaVersions` the issue should be fixed, because the first JDK defined (in the case of this PR, JDK 21) is the one used for the publish job. I'm pretty sure that this doesn't affect anything else because we're only using a newest …
=> Plugin dependencies under `sbt-typelevel` umbrella

modules/core/src/main/scala/fs2/kafka/CommitRecovery.scala, modules/core/src/test/scala/fs2/kafka/CommitRecoverySpec.scala
Fixes #1213 
After inspecting the internals of Kafka Client's `KafkaConsumer`, any time a `RebalanceInProgressException` is thrown, the message states it can be retried after a call to `poll()`. 
https://github.com/apache/kafka/blob/5e3c2b738d253ff51a7a61fe08713f564ab647fa/clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerCoordinator.java#L1347
https://github.com/apache/kafka/blob/5e3c2b738d253ff51a7a61fe08713f564ab647fa/clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerCoordinator.java#L1437
https://github.com/apache/kafka/blob/5e3c2b738d253ff51a7a61fe08713f564ab647fa/clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerCoordinator.java#L1457
https://github.com/apache/kafka/blob/5e3c2b738d253ff51a7a61fe08713f564ab647fa/c …
=> Retry `RebalanceInProgressException` in `CommitRecovery.Default`

modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala
Some context to start: Cats Effects has been having memory leaks in CallbackStack since version 3.4.3.
See for example: https://github.com/typelevel/cats-effect/issues/3935
I've been facing this memory leak in an application using fs2-kafka, and found that I'm not the only one (https://github.com/typelevel/cats-effect/pull/3973).
Using a simple consumer > produce stream application, I monitored the size of the CallbackStack using the following command:
```
while sleep 1; do jcmd <pid> GC.class_histogram | grep 'cats.effect.CallbackStack$Node' ; done
```
I found that swapping the `F.race(shutdown, fetch)` for `fetch` stops the memory leak. This should not be an issue because the Stream is anyway interrupted on `.interruptWhen(F.race(shutdown, stopReqs.get).void.attempt)`, but I'm not 100% …
=> fix: memory leak in Cats Effects

modules/core/src/main/scala/fs2/kafka/KafkaProducer.scala, modules/core/src/main/scala/fs2/kafka/KafkaProducerConnection.scala, modules/core/src/main/scala/fs2/kafka/ProducerSettings.scala, modules/core/src/main/scala/fs2/kafka/TransactionalKafkaProducer.scala, modules/core/src/main/scala/fs2/kafka/producer/MkProducer.scala, modules/core/src/test/scala/fs2/kafka/BaseKafkaSpec.scala, modules/core/src/test/scala/fs2/kafka/KafkaProducerSpec.scala, modules/core/src/test/scala/fs2/kafka/ProducerSettingsSpec.scala, modules/core/src/test/scala/fs2/kafka/TransactionalKafkaProducerSpec.scala
Introduce `KafkaProducer.failFastProduce` producer configuration:
https://github.com/fd4s/fs2-kafka/blob/aed7ab3aeda58ac3b32438c5c22fb91c86ee2426/modules/core/src/main/scala/fs2/kafka/ProducerSettings.scala#L218-L228
When `failFastProduce` is set to true, each `fs2.kafka.producer.produce` call of `ProducerRecords` creates a `scala.concurrent.Promise[Throwable]`. This Promise resolution is raced against calling `org.apache.kafka.clients.producer.KafkaProducer.send` per record. Any failing callback will complete the promise with the failure, canceling the rest of the pending `org.apache.kafka.clients.producer.KafkaProducer.send` and in-flight callbacks.
https://github.com/fd4s/fs2-kafka/blob/2559d96ce326f9f2ffc2936c1b9b5f3086a7829c/modules/core/src/main/scala/fs2/kafka/KafkaProducer.scala#L1 …
=> KafkaProducer.produce fails fast

modules/core/src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
When running tests locally some times this test would fail, seemingly because all records were produced with the same timestamp, such that there were no records with `earliestTimestamp + 1`.
By producing records in two chunks I stopped seeing these spurious failures locally.
=> chore: improve flaky test

modules/core/src/main/scala/fs2/kafka/consumer/MkConsumer.scala
I've got this warning by ce3 blocking detection 
```
[WARNING] A Cats Effect worker thread was detected to be in a blocked state (BLOCKED)                                                    │
│   at org.apache.kafka.common.metrics.JmxReporter.reconfigure(JmxReporter.java:109)                                                       │
│   at org.apache.kafka.common.metrics.JmxReporter.configure(JmxReporter.java:93)                                                          │
│   at org.apache.kafka.clients.CommonClientConfigs.metricsReporters(CommonClientConfigs.java:243)                                         │
│   at org.apache.kafka.clients.CommonClientConfigs.metricsReporters(CommonClientConfigs.java:234)                                         │
│   at …
```
=> Instantiate underlying Kafka Consumer inside blocking context

modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala, modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala
`KafkaConsumerActor.manualCommitAsync` no longer semantically blocks the actor polling loop. It shares the same implementation as `CommittableConsumerRecord.commit`, except it does not apply the commit recovery policy. Instead, it leverages the existing queue mechanism rather than spawning a new fiber. 
The combination of actor blocking and fiber spawning is assumed to contribute to the observed performance degradation.
In our model, we manage over 1,000 integrations, where each integration translates to **N Kafka consumers** (where N is the number of partitions per topic) assigned—not subscribed—to the respective topics. On average, each topic has 24 partitions, resulting in approximately **24,000 active consumers**.  
Previously, we used `CommitBatch.commit` and observed **p95 …
=> Simply `KafkaConsumer.commitAsync`

modules/core/src/main/scala/fs2/kafka/KafkaProducer.scala
Using `tryFailure` instead of `failure` will not produce an `IllegalStateException` when the sending of multiple records is interrupted. The same promise is used for all records and all of them will complete that same promise, leading to the exception without this change.
This fixes issue #1391.
=> Fix exeption of multiple promise completions (#1391)

modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala, modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, modules/core/src/main/scala/fs2/kafka/internal/LogEntry.scala
Record streams are streamlined by dropping the `FetchRequest` middleman. Instead, queues of records are lazily created by `KafkaConsumerActor`, one for each assigned partition.
Enqueueing records uses `Queue.tryOffer`, to avoid blocking the polling fiber. `KafkaConsumerActor` maintains a separate `spillover` map to hold records when queues are full. This acts as back-pressure and pauses polling for "slow" partitions.
`KafkaConsumerActor.poll` takes a more active role in managing assigned partitions. Namely, it signals the revocation of any partitions that are not assigned, and drops those from the internal state.
While the `ConsumerRebalanceListener` interface is meant to handle this state when the consumer faces rebalance operations, explicitly handling assignments in `poll` caters to …
=> feat: drop use of FetchRequests

modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, modules/core/src/main/scala/fs2/kafka/internal/LogEntry.scala
This is a combination of two related changes to the handling of pending commits during rebalance operations in `KafkaConsumerActor`.
Whether immediately committing offsets, or queueing the request in `State.pendingCommits`, the necessary effect is built at once.
This avoids the need to repeat similar logic in disparate call sites, and makes visible in a single place how the request will be processed and logged.
Commits would be added to the chain of pending commits based only on the rebalancing state. Given that the rebalancing state is updated (via `ConsumerRebalanceListener.onPartitionsAssigned`) separate from when pending commits are processed (after `poll`), it could happen that commits emitted later would be processed before earlier pending ones.
This updates the condition for …
=> chore: tweaks to handling of pending commits

modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala
In the face of backpressure, spillover records that couldn't be offered to the queue would be registered, and wouldn't always be cleared afterwards, leading to duplicate records being offered. This is addressed by ensuring spillover records are always reset at the end of the poll loop.
In an earlier iteration of #1369 spillover records were reset early in the poll loop. At the end of the loop only remaining spillover records needed to be recorded. In the approach that ended up being submitted spillover records are reset only once at the end of the poll loop, but logic from the earlier iteration was inadvertently left behind that skipped this reset operation in the case there were no remaining spillover records to register.
=> fix: reset spillover after poll loop

docs/src/main/mdoc/producers.md, modules/core/src/main/scala/fs2/kafka/ProducerSettings.scala
This was introduced due to the default behavior of Kafka prior to version 3.0. However, it now causes more harm than good by preventing fail-safe behavior during rebalancing, as `NotLeaderOrFollowerException` is not retried.
Since Kafka 3.0, the default is `enable.idempotence=true`, which ensures safe behavior according to both the SoftwareMill blog (mentioned in producers.md) and the [Kafka docs](https://kafka.apache.org/documentation/#producerconfigs_retries).
> Allowing retries while setting enable.idempotence to false and max.in.flight.requests.per.connection to greater than 1 will potentially change the ordering of records because if two batches are sent to a single partition, and the first fails and is retried but the second succeeds, then the records in the second batch may appear …
=> removed `retries` value override

build.sbt, docs/src/main/mdoc/consumers.md, modules/core/src/main/scala/fs2/kafka/ConsumerSettings.scala, modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala, modules/core/src/main/scala/fs2/kafka/RebalanceRevokeMode.scala, modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala, modules/core/src/main/scala/fs2/kafka/internal/LogEntry.scala, modules/core/src/test/scala/fs2/kafka/KafkaConsumerSpec.scala
This is potential solution for https://github.com/fd4s/fs2-kafka/issues/1200. Allowing for opting-in for graceful revoke handling (waiting for all the streams to finish, which should imply all the commits as well)
=> feat: Implemented RebalanceRevokeMode
